INSERT INTO db_fotoalbum.fotos (description, image_url, title, visible)VALUES ('Meravigliosa cena romantica con vista sulla Torre Eiffel', 'https://picsum.photos/id/10/600/700', 'Cena romantica a Parigi', 1);
INSERT INTO db_fotoalbum.fotos (description, image_url, title, visible)VALUES ('Escursione emozionante nelle foreste pluviali dell\'Amazzonia', 'https://picsum.photos/id/13/600/700', 'Avventura in Amazzonia', 1);
INSERT INTO db_fotoalbum.fotos (description, image_url, title, visible)VALUES ('Esplorazione delle antiche rovine di Machu Picchu al tramonto', 'https://picsum.photos/id/28/600/700', 'Viaggio a Machu Picchu', 1);
INSERT INTO db_fotoalbum.fotos (description, image_url, title, visible)VALUES ('Tour gastronomico attraverso le strade di Napoli', 'https://picsum.photos/id/29/600/700', 'Giro culinario a Napoli', 1);
INSERT INTO db_fotoalbum.fotos (description, image_url, title, visible)VALUES ('Incredibile immersione tra i coralli della Grande Barriera Corallina', 'https://picsum.photos/id/37/600/700', 'Subacquea in Australia', 1);
INSERT INTO db_fotoalbum.fotos (description, image_url, title, visible)VALUES ('Spettacolare tramonto sulla spiaggia di Bora Bora', 'https://picsum.photos/id/43/600/700', 'Tramonto a Bora Bora', 1);
INSERT INTO db_fotoalbum.fotos (description, image_url, title, visible)VALUES ('Tour enogastronomico nelle colline toscane', 'https://picsum.photos/id/46/600/700', 'Viaggio enogastronomico in Toscana', 1);
INSERT INTO db_fotoalbum.fotos (description, image_url, title, visible)VALUES ('Esplorazione della Città Proibita a Pechino', 'https://picsum.photos/id/49/600/700', 'Viaggio a Pechino', 1);
INSERT INTO db_fotoalbum.fotos (description, image_url, title, visible)VALUES ('Fascinante passeggiata lungo il Canal Grande a Venezia', 'https://picsum.photos/id/71/600/700', 'Venezia romantica', 1);
INSERT INTO db_fotoalbum.fotos (description, image_url, title, visible)VALUES ('Escursione tra i vigneti della Valle della Loira', 'https://picsum.photos/id/74/600/700', 'Tour dei vigneti in Valle della Loira', 1);
INSERT INTO db_fotoalbum.categories (description, name) VALUES('Foto di feste e eventi vari', 'Festa');
INSERT INTO db_fotoalbum.categories (description, name) VALUES ('Foto di paesaggi naturali', 'Natura');
INSERT INTO db_fotoalbum.categories (description, name) VALUES ('Scatti artistici in bianco e nero', 'Arte');
INSERT INTO db_fotoalbum.categories (description, name) VALUES ('Ritratti di persone famose', 'Ritratti');
INSERT INTO db_fotoalbum.categories (description, name) VALUES ('Momenti sportivi indimenticabili', 'Sport');
INSERT INTO db_fotoalbum.categories (description, name) VALUES ('Esperienze culinarie nel mondo', 'Cibo');
INSERT INTO db_fotoalbum.categories (description, name) VALUES ('Viaggi avventurosi in luoghi remoti', 'Avventura');
INSERT INTO db_fotoalbum.categories (description, name) VALUES ('Instantanea di vita quotidiana', 'Vita quotidiana');
INSERT INTO db_fotoalbum.categories (description, name) VALUES ('Manifestazioni culturali e tradizioni', 'Cultura');
INSERT INTO db_fotoalbum.categories (description, name) VALUES ('Momenti dolci e romantici', 'Amore');
INSERT INTO roles (id, name) VALUES(1, 'ADMIN');
INSERT INTO roles (id, name) VALUES(2, 'SUPER_ADMIN');
INSERT INTO users (email, first_name, last_name, registered_at, password) VALUES('gino@email.com', 'Gino', 'BuonVino', '2023-11-24 10:35', '{noop}gino');
INSERT INTO users (email, first_name, last_name, registered_at, password) VALUES('jane@email.com', 'Jane', 'Smith', '2023-11-24 10:35','{noop}jane');
INSERT INTO users_roles (user_id, roles_id) VALUES(1, 2);
INSERT INTO users_roles (user_id, roles_id) VALUES(2, 1);